name: Pull Request Validation

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check PR Title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          # Prüfe PR-Titel-Format
          if [[ ! "$PR_TITLE" =~ ^(feat|fix|docs|style|refactor|test|chore|build|ci)(\(.+\))?:\ .+ ]]; then
            echo "PR-Titel entspricht nicht dem konventionellen Format:"
            echo "Erwartetes Format: <type>(<scope>): <description>"
            echo "Beispiele:"
            echo "- feat: add new music playback feature"
            echo "- fix(player): resolve audio skipping issue"
            exit 1
          fi

      - name: Check PR Description
        env:
          PR_BODY: ${{ github.event.pull_request.body }}
        run: |
          # Prüfe, ob Beschreibung Mindestanforderungen erfüllt
          if [[ -z "$PR_BODY" ]]; then
            echo "Pull Request benötigt eine Beschreibung!"
            echo "Bitte füge eine detaillierte Beschreibung hinzu:"
            echo "- Was wurde geändert?"
            echo "- Warum wurde es geändert?"
            echo "- Gibt es besondere Hinweise?"
            exit 1
          fi

          # Optional: Prüfe Mindestlänge der Beschreibung
          BODY_LENGTH=$(echo "$PR_BODY" | wc -c)
          if [[ $BODY_LENGTH -lt 50 ]]; then
            echo "Pull Request Beschreibung zu kurz. Bitte gib mehr Details."
            exit 1
          fi